export const MENU_ITEM_ROUTE = [
  {
    id: 1,
    permission: [],
    title: 'Dashboard',
    icon: '',
    url: '/dashboard',
    showable: true,
  },
  {
    id: 2,
    permission: [],
    title: 'Clients',
    icon: '',
    url: '/clients',
    showable: true,
  },
  {
    id: 3,
    permission: [],
    title: 'Goals',
    icon: '',
    url: '/goals',
    showable: true,
  },
  {
    id: 4,
    permission: [],
    title: 'Transaction Wizard',
    icon: '',
    url: '/transaction-wizard',
    showable: true,
  },
  {
    id: 5,
    permission: [],
    title: 'Reports',
    icon: '',
    url: '/reports',
    showable: true,
  },
  {
    id: 6,
    permission: [],
    title: 'Settings',
    icon: '',
    url: '/settings',
    showable: true,
  },
];
