name: DEV ACTIONS

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Deploy Code
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/.ssh

            # Use the existing SSH key named 'github'
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github
            chmod 600 ~/.ssh/github

            # Configure SSH to use the correct key for GitHub
            echo "Host github.com
            IdentityFile ~/.ssh/github
            StrictHostKeyChecking no" > ~/.ssh/config

            # Add GitHub's host key to known_hosts to prevent confirmation prompt
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            # Test SSH connection with GitHub
            ssh -i ~/.ssh/github -T git@github.com || exit 1
            set -e  # Exit on any error

            # Path to the .env file in the project directory
            ENV_FILE="/www/finanzoweb/.env"

            # Clear or create new .env file
            : > $ENV_FILE

            # Write all secrets to the .env file
            echo "NEXT_PUBLIC_API_URL=${{ vars.DEV_NEXT_PUBLIC_API_URL }}" >> $ENV_FILE
            echo "NEXT_PUBLIC_SOCKET_URL=${{ vars.DEV_NEXT_PUBLIC_SOCKET_URL }}" >> $ENV_FILE
            echo "NEXT_PUBLIC_AZURE_AD_CLIENT_ID=${{ secrets.DEV_NEXT_PUBLIC_AZURE_AD_CLIENT_ID }}" >> $ENV_FILE
            echo "NEXT_PUBLIC_AZURE_AD_TENANT_ID=${{ secrets.DEV_NEXT_PUBLIC_AZURE_AD_TENANT_ID }}" >> $ENV_FILE
            echo "NEXT_PUBLIC_AZURE_AD_REDIRECT_URI=${{ vars.DEV_NEXT_PUBLIC_AZURE_AD_REDIRECT_URI }}" >> $ENV_FILE
            echo "NEXT_PUBLIC_AZURE_AD_AUTHORITY=${{ secrets.DEV_NEXT_PUBLIC_AZURE_AD_AUTHORITY }}" >> $ENV_FILE
            echo "NEXT_PUBLIC_AZURE_AD_SCOPES=${{ vars.DEV_NEXT_PUBLIC_AZURE_AD_SCOPES }}" >> $ENV_FILE

            # adb2c vars and secrets for .env file
            echo "NEXT_PUBLIC_B2C_CLIENT_ID=${{ secrets.NEXT_PUBLIC_B2C_CLIENT_ID }}" >> $ENV_FILE
            echo "NEXT_PUBLIC_B2C_AUTHORITY=${{ vars.NEXT_PUBLIC_B2C_AUTHORITY }}" >> $ENV_FILE
            echo "NEXT_PUBLIC_B2C_KNOWN_AUTHORITY=${{ vars.NEXT_PUBLIC_B2C_KNOWN_AUTHORITY }}" >> $ENV_FILE
            echo "NEXT_PUBLIC_B2C_SIGNUP_AUTHORITY=${{ vars.NEXT_PUBLIC_B2C_SIGNUP_AUTHORITY }}" >> $ENV_FILE
            echo "NEXT_PUBLIC_REDIRECT_URI=${{ vars.NEXT_PUBLIC_REDIRECT_URI }}" >> $ENV_FILE

            # Continue the further Deployment process  
            expor
